plugins {
    id 'com.android.application'
}

android {
    namespace 'com.kameko.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.kameko.app"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        debug {}
    }
}
